# Generated by Django 5.1 on 2024-08-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_test', '0002_testresult_current_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='score',
        ),
    ]
