services:

  backend:
    build: ./
    container_name: backend
    restart: always
    ports:
      - "8010:8000"
    volumes:
      - ./src:/srv/project
    env_file:
      - .env
    depends_on:
      - postgresql


  postgresql:
    image: "postgres:13"
    container_name: postgresql
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  pgdata: {}